name: Erlang CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: ["erlang:22"]
        
    container:
      image: ${{ matrix.otp }}        

    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: make
    - name: Run tests
      run: make test
